spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/userdb
    username: root
    password: 1qa2ws3ed

  session:
    store-type: redis

  redis:
    host: 47.102.192.55
    port: 6380
    password:
    database: 0

  cloud:
    kubernetes:
      discovery:
        all-namespaces: true


server:
  port: 9999